### ISSUE TITLE
The pacakge file's sha256 is mismatch with the sha256 provied in repo

### ISSUE THREAD

**Issue by Misaka-L** [z3y/vpm-package-listing#1]
I have already make a pull request on PiMaker's package list action: https://github.com/PiMaker/package-list-action/pull/1

since [vrc-get](https://github.com/vrc-get/vrc-get) may refused to install package which file's sha256 is mismatched with repo's sha256: https://github.com/vrc-get/vrc-get/pull/1183

I think you should take a look at it.

@z3y

**Comment by z3y** [comment]
thank you i updated the package list action
